//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMangement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int serID { get; set; }
        public Nullable<int> book_ID { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<int> product_ID { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<System.DateTime> Buy_Date { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
