//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMangement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Show_CustomerCheckOut
    {
        public int cID { get; set; }
        public string Fullname { get; set; }
        public string Email { get; set; }
        public string Phone_Number { get; set; }
        public string room_No { get; set; }
        public Nullable<System.DateTime> Check_In { get; set; }
        public Nullable<System.DateTime> Check_Out { get; set; }
    }
}
