//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMangement
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_PRODUCT
    {
        public int pID { get; set; }
        public Nullable<int> cate_ID { get; set; }
        public string Title { get; set; }
        public string Thumbnail { get; set; }
        public string Decription { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Amount { get; set; }
    }
}
