//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMangement
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Receipt
    {
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string EmployeeName { get; set; }
        public string room_No { get; set; }
        public Nullable<int> RoomCapacity { get; set; }
        public Nullable<int> StayingDays { get; set; }
        public string Service { get; set; }
        public Nullable<double> ServicePrice { get; set; }
        public Nullable<int> ServiceQuantity { get; set; }
        public Nullable<double> ServiceTotal { get; set; }
        public Nullable<double> RoomPrice { get; set; }
        public Nullable<double> RoomUnit { get; set; }
    }
}
